[env:esp32dev]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
  -DAPP_VERSION=\"0.1.0\"
  -DARDUINO_LOOP_STACK_SIZE=8192
  -DMACROPAD_ENABLE_BOOT_HOLD_FACTORY_RESET=0
  -DMACROPAD_BLE_STRICT_AUTH=0
  -DMACROPAD_AP_START_ON_BOOT=0
  -DCONFIG_ASYNC_TCP_STACK_SIZE=4096
lib_deps =
  t-vk/ESP32 BLE Keyboard@^0.3.2
  https://github.com/esphome/ESPAsyncWebServer.git#v3.0.0
  bblanchon/ArduinoJson@^7.0.4
  olikraus/U8g2@^2.36.18
  mathertel/RotaryEncoder@^1.6.0
